batch:
  maxConcurrentDownloads: 5
  targetRegistry: registry.saas.hand-china.com/hxd
  images:
    - "registry.cn-hangzhou.aliyuncs.com/choerodon-tools/gitlab-ce"
  # - "mysql:5.7.24"
  # - "nginx:1.15.7"
# single:
#   - image: "tomcat:7.0.92-jre8"
#     targetRegistry: registry.saas.hand-china.com/tools
