version: 2
jobs:
  build:
    docker:
      - image: setzero/mirror-docker-image:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run : |
          docker login -u $REGISTRY_SAAS_USER -p $REGISTRY_SAAS_PWD $REGISTRY_SAAS
          mirror
